### ISSUE TITLE
CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/pts...

### ISSUE THREAD

**Issue by kevinkle** [superphy/spfy#307]
https://sentry.io/superphy/spfy/issues/582977144/

```
CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
  File "rq/worker.py", line 700, in perform_job
    rv = job.perform()
  File "rq/job.py", line 500, in perform
    self._result = self.func(*self.args, **self.kwargs)
  File "modules/phylotyper/phylotyper.py", line 101, in phylotyper
    stderr=subprocess.STDOUT)
  File "python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)

CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
```

**Comment by kevinkle** [comment]
```bash
worker-phylotyper_1      | INFO:phylotyper.main:Config:
worker-phylotyper_1      | R:
worker-phylotyper_1      |     rscript: Rscript
worker-phylotyper_1      |     repo: None
worker-phylotyper_1      |     lib: None
worker-phylotyper_1      | external:
worker-phylotyper_1      |     blastx: blastx
worker-phylotyper_1      |     blastdbcmd: blastdbcmd
worker-phylotyper_1      |     makeblastdb: makeblastdb
worker-phylotyper_1      |     fasttree: FastTree
worker-phylotyper_1      |     trimal: trimal
worker-phylotyper_1      |     blastn: blastn
worker-phylotyper_1      |     mafft: mafft
worker-phylotyper_1      | phylotyper:
worker-phylotyper_1      |     prediction_threshold: 0.9
worker-phylotyper_1      |
worker-phylotyper_1      | INFO:phylotyper.genome.loci.LociSearch:1 hits found for loci 1 after filtering overlapping hits
worker-phylotyper_1      | 	(spfy|c5c07ff7b6a67c25a166939530761bbc7e078243/contigs/gi1108586541gbCP013185.1/stx2A/3279680_3280639| gi|1108586541|gb|CP013185.1|:3279680..3280639:1-960)
worker-phylotyper_1      | Traceback (most recent call last):
worker-phylotyper_1      |   File "/opt/conda/envs/backend/bin/phylotyper", line 11, in <module>
worker-phylotyper_1      |     sys.exit(main())
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/phylotyper-0.1.0-py2.7.egg/phylotyper/run.py", line 698, in main
worker-phylotyper_1      |     subtype_pipeline(subtype_options, config)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/phylotyper-0.1.0-py2.7.egg/phylotyper/run.py", line 226, in subtype_pipeline
worker-phylotyper_1      |     remaining = identical_sequences(options, assignments)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/phylotyper-0.1.0-py2.7.egg/phylotyper/run.py", line 394, in identical_sequences
worker-phylotyper_1      |     supersequences, incomplete = concat.load(options['input'], missing='warn')
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/phylotyper-0.1.0-py2.7.egg/phylotyper/tree/seq.py", line 443, in load
worker-phylotyper_1      |     for record in fasta:
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/Bio/SeqIO/__init__.py", line 581, in parse
worker-phylotyper_1      |     with as_handle(handle, mode) as fp:
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/contextlib.py", line 17, in __enter__
worker-phylotyper_1      |     return self.gen.next()
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/Bio/File.py", line 88, in as_handle
worker-phylotyper_1      |     with open(handleish, mode, **kwargs) as fp:
worker-phylotyper_1      | IOError: [Errno 2] No such file or directory: '/datastore/ptstx2I2yYBQ/search_results.locus1'
worker-phylotyper_1      | 18:18:41 CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | Traceback (most recent call last):
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
worker-phylotyper_1      |     rv = job.perform()
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
worker-phylotyper_1      |     self._result = self.func(*self.args, **self.kwargs)
worker-phylotyper_1      |   File "./modules/phylotyper/phylotyper.py", line 101, in phylotyper
worker-phylotyper_1      |     stderr=subprocess.STDOUT)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/subprocess.py", line 186, in check_call
worker-phylotyper_1      |     raise CalledProcessError(retcode, cmd)
worker-phylotyper_1      | CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | Traceback (most recent call last):
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
worker-phylotyper_1      |     rv = job.perform()
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
worker-phylotyper_1      |     self._result = self.func(*self.args, **self.kwargs)
worker-phylotyper_1      |   File "./modules/phylotyper/phylotyper.py", line 101, in phylotyper
worker-phylotyper_1      |     stderr=subprocess.STDOUT)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/subprocess.py", line 186, in check_call
worker-phylotyper_1      |     raise CalledProcessError(retcode, cmd)
worker-phylotyper_1      | CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | 2018-06-17 18:18:41,955 rq.worker    ERROR    CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | Traceback (most recent call last):
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
worker-phylotyper_1      |     rv = job.perform()
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
worker-phylotyper_1      |     self._result = self.func(*self.args, **self.kwargs)
worker-phylotyper_1      |   File "./modules/phylotyper/phylotyper.py", line 101, in phylotyper
worker-phylotyper_1      |     stderr=subprocess.STDOUT)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/subprocess.py", line 186, in check_call
worker-phylotyper_1      |     raise CalledProcessError(retcode, cmd)
worker-phylotyper_1      | CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | Traceback (most recent call last):
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/worker.py", line 700, in perform_job
worker-phylotyper_1      |     rv = job.perform()
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/site-packages/rq/job.py", line 500, in perform
worker-phylotyper_1      |     self._result = self.func(*self.args, **self.kwargs)
worker-phylotyper_1      |   File "./modules/phylotyper/phylotyper.py", line 101, in phylotyper
worker-phylotyper_1      |     stderr=subprocess.STDOUT)
worker-phylotyper_1      |   File "/opt/conda/envs/backend/lib/python2.7/subprocess.py", line 186, in check_call
worker-phylotyper_1      |     raise CalledProcessError(retcode, cmd)
worker-phylotyper_1      | CalledProcessError: Command '['phylotyper', 'genome', '--noplots', 'stx2', '/datastore/ptstx2I2yYBQ', '/datastore/ptstx2I2yYBQ/query.fasta']' returned non-zero exit status 1
worker-phylotyper_1      | 18:18:42 Moving job to u'failed' queue
worker-phylotyper_1      | 2018-06-17 18:18:42,191 rq.worker    WARNING  Moving job to u'failed' queue
worker-phylotyper_1      | 18:18:42
worker-phylotyper_1      | 18:18:42 *** Listening on phylotyper, backlog_phylotyper...
worker-phylotyper_1      | INFO:phylotyper.main:No config file argument. Using default settings.
worker-phylotyper_1      | You can provide a Phylotyper config file using enviroment variable PHYLOTYPER_CONFIG or command-line argument --config.
```

**Comment by kevinkle** [comment]
Fixed in https://github.com/superphy/spfy/pull/309
